### ISSUE TITLE
Content served over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by zandorol** [kennibc/moodle-theme_pioneer#12]
I am having trouble with using the Pioneer theme on a Moodle site with https.

When loading the website, the theme is not being fetched and I get a lot of warnings in Chrome like this one:
`Mixed Content: The page at 'https://example.com/my/' was loaded over HTTPS, but requested an insecure image 'http://example.com/theme/image.php/pioneer/core/1464080915/u/f2'. This content should also be served over HTTPS.`

Maybe you can point me in the direction on how to fix this issue.
I am using Pioneer 1.4.0 with Moodle 3.0.4+ (Build: 20160520) Version 2015111604.08 Stable Version.

**Comment by zandorol** [comment]
Apparently this was fixed by setting `$CFG->sslproxy = 1;` in config.php of Moodle.

**Comment by kennibc** [comment]
Thanks!  I was just looking into this because we use SSL.

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
*Michigan Moodle User group
<https://www.facebook.com/groups/819830188053375/> (Facebook)*
*Michigan Moodle User Group
<https://plus.google.com/u/0/communities/113077058997214337239> (Google +)*
http://iblog.dearbornschools.org/technology
http://webmaster.dearbornschools.org
